// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Util$ReasonTree = require("./Util.bs.js");

console.log(Util$ReasonTree.printDir(0, "node_modules", "../"));

/*  Not a pure module */
