// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

function getAbsolutePath(path) {
  return Path.resolve(__dirname, path);
}

exports.getAbsolutePath = getAbsolutePath;
/* path Not a pure module */
