// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var List = require("bs-platform/lib/js/list.js");
var Path = require("path");
var $$Array = require("bs-platform/lib/js/array.js");

function getAbsolutePath(path) {
  return Path.resolve(__dirname, path);
}

function printDir(dirPath) {
  var absolutePath = Path.resolve(__dirname, dirPath);
  var contentArray = Fs.readdirSync(absolutePath);
  var contentList = $$Array.to_list(contentArray);
  return List.iter((function (item) {
                console.log("name: " + item);
                return /* () */0;
              }), contentList);
}

exports.getAbsolutePath = getAbsolutePath;
exports.printDir = printDir;
/* fs Not a pure module */
